"""initial schema

Revision ID: 22891c4578b0
Revises:
Create Date: 2026-08-20 23:55:49.774136
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "22891c4578b0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=80), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_hash"),
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_org_created", "audit_events", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint", sa.String(length=160), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "endpoint", "key"),
    )
    op.create_index(
        op.f("ix_idempotency_records_organization_id"),
        "idempotency_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "UPLOADER",
                "ANALYST",
                "APPROVER",
                "AUDITOR",
                "ADMIN",
                name="role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id"),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "rescue_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=180), nullable=False),
        sa.Column("applicant_company", sa.String(length=180), nullable=False),
        sa.Column("erp_provider", sa.String(length=120), nullable=False),
        sa.Column("assigned_analyst_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_approver_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "EVIDENCE_REVIEW",
                "READY_FOR_INTERNAL_REVIEW",
                "INTERNAL_PACKET_APPROVED",
                "EXPORTED",
                "ARCHIVED",
                name="casestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_revision_number", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assigned_analyst_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["assigned_approver_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rescue_cases_org_status", "rescue_cases", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_rescue_cases_organization_id"), "rescue_cases", ["organization_id"], unique=False
    )
    op.create_table(
        "case_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("previous_revision_id", sa.String(length=36), nullable=True),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["rescue_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["previous_revision_id"], ["case_revisions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "number"),
    )
    op.create_index(op.f("ix_case_revisions_case_id"), "case_revisions", ["case_id"], unique=False)
    op.create_table(
        "calculation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_revision_id", sa.String(length=36), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("engine_version", sa.String(length=40), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("result_snapshot", sa.JSON(), nullable=False),
        sa.Column("result_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_revision_id"], ["case_revisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calculation_runs_case_revision_id"),
        "calculation_runs",
        ["case_revision_id"],
        unique=False,
    )
    op.create_table(
        "contract_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("case_revision_id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column(
            "safety_status",
            sa.Enum("PENDING", "PASSED", "REJECTED", name="safetystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "processing_status",
            sa.Enum(
                "UPLOADED",
                "PROCESSING",
                "PROCESSED",
                "NEEDS_OCR",
                "FAILED",
                name="processingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_revision_id"], ["case_revisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "sha256", "case_revision_id"),
        sa.UniqueConstraint("stored_filename"),
    )
    op.create_index(
        op.f("ix_contract_documents_case_revision_id"),
        "contract_documents",
        ["case_revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_documents_organization_id"),
        "contract_documents",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_documents_sha256"), "contract_documents", ["sha256"], unique=False
    )
    op.create_table(
        "fee_obligations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_revision_id", sa.String(length=36), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "SUBSCRIPTION",
                "TAX",
                "PENALTY",
                "PROFESSIONAL_SERVICE",
                "IMPLEMENTATION",
                "TERMINATION",
                "OTHER",
                "UNCLASSIFIED",
                name="feecategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("service_start", sa.Date(), nullable=True),
        sa.Column("service_end", sa.Date(), nullable=True),
        sa.Column("obligation_date", sa.Date(), nullable=True),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("billing_cadence", sa.String(length=30), nullable=True),
        sa.Column("proration_rule", sa.String(length=80), nullable=True),
        sa.Column("assertion_ids", sa.JSON(), nullable=False),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_revision_id"], ["case_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fee_obligations_case_revision_id"),
        "fee_obligations",
        ["case_revision_id"],
        unique=False,
    )
    op.create_table(
        "readiness_findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_revision_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("BLOCKING", "WARNING", "INFO", name="findingseverity", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "RESOLVED", "ACCEPTED_RISK", name="findingstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_revision_id"], ["case_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_readiness_findings_case_revision_id"),
        "readiness_findings",
        ["case_revision_id"],
        unique=False,
    )
    op.create_table(
        "calculation_line_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("calculation_id", sa.String(length=36), nullable=False),
        sa.Column("fee_obligation_id", sa.String(length=36), nullable=True),
        sa.Column("treatment", sa.String(length=30), nullable=False),
        sa.Column("original_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("remaining_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("formula_identifier", sa.String(length=80), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["calculation_id"], ["calculation_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fee_obligation_id"], ["fee_obligations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calculation_line_items_calculation_id"),
        "calculation_line_items",
        ["calculation_id"],
        unique=False,
    )
    op.create_table(
        "document_pages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["contract_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page_number"),
    )
    op.create_index(
        op.f("ix_document_pages_document_id"), "document_pages", ["document_id"], unique=False
    )
    op.create_table(
        "export_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_revision_id", sa.String(length=36), nullable=False),
        sa.Column("calculation_id", sa.String(length=36), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "INTERNAL_REVIEW_PDF",
                "CUSTOMER_EXPLANATION_PDF",
                "EVIDENCE_CSV",
                "MACHINE_READABLE_JSON",
                name="exportkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("packet_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("revision_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("approval_status", sa.String(length=20), nullable=False),
        sa.Column("approval_case_version", sa.Integer(), nullable=True),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prepared_by", sa.String(length=36), nullable=False),
        sa.Column("generator_version", sa.String(length=40), nullable=False),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["calculation_id"], ["calculation_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["case_revision_id"], ["case_revisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["prepared_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_filename"),
    )
    op.create_index(
        op.f("ix_export_artifacts_case_revision_id"),
        "export_artifacts",
        ["case_revision_id"],
        unique=False,
    )
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.String(length=30), nullable=False),
        sa.Column("extractor", sa.String(length=120), nullable=False),
        sa.Column("model_identifier", sa.String(length=160), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("code_version", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING", "SUCCEEDED", "FAILED", name="extractionrunstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("structured_output_hash", sa.String(length=64), nullable=True),
        sa.Column("error_category", sa.String(length=80), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["contract_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_runs_document_id"), "extraction_runs", ["document_id"], unique=False
    )
    op.create_table(
        "contract_assertions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_revision_id", sa.String(length=36), nullable=False),
        sa.Column("extraction_run_id", sa.String(length=36), nullable=True),
        sa.Column("semantic_key", sa.String(length=100), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.JSON(), nullable=False),
        sa.Column("display_value", sa.Text(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "DETERMINISTIC", "AI", "HUMAN", "DERIVED", name="assertionsource", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "review_state",
            sa.Enum(
                "PROPOSED",
                "ACCEPTED",
                "CORRECTED",
                "REJECTED",
                "CONFLICTING",
                name="assertionreviewstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("supersedes_assertion_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_revision_id"], ["case_revisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["extraction_run_id"], ["extraction_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["supersedes_assertion_id"], ["contract_assertions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_revision_id", "semantic_key", "version"),
    )
    op.create_index(
        "ix_assertions_revision_current",
        "contract_assertions",
        ["case_revision_id", "is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_assertions_case_revision_id"),
        "contract_assertions",
        ["case_revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_assertions_semantic_key"),
        "contract_assertions",
        ["semantic_key"],
        unique=False,
    )
    op.create_table(
        "evidence_spans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("page_id", sa.String(length=36), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("quote_sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["document_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assertion_evidence_links",
        sa.Column("assertion_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["assertion_id"], ["contract_assertions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence_spans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("assertion_id", "evidence_id"),
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assertion_id", sa.String(length=36), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("ACCEPT", "CORRECT", "REJECT", name="reviewdecisiontype", native_enum=False),
            nullable=False,
        ),
        sa.Column("reviewer_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("corrected_value", sa.JSON(), nullable=True),
        sa.Column("assumption", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assertion_id"], ["contract_assertions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_decisions_assertion_id"), "review_decisions", ["assertion_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_decisions_assertion_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_table("assertion_evidence_links")
    op.drop_table("evidence_spans")
    op.drop_index(op.f("ix_contract_assertions_semantic_key"), table_name="contract_assertions")
    op.drop_index(op.f("ix_contract_assertions_case_revision_id"), table_name="contract_assertions")
    op.drop_index("ix_assertions_revision_current", table_name="contract_assertions")
    op.drop_table("contract_assertions")
    op.drop_index(op.f("ix_extraction_runs_document_id"), table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_index(op.f("ix_export_artifacts_case_revision_id"), table_name="export_artifacts")
    op.drop_table("export_artifacts")
    op.drop_index(op.f("ix_document_pages_document_id"), table_name="document_pages")
    op.drop_table("document_pages")
    op.drop_index(
        op.f("ix_calculation_line_items_calculation_id"), table_name="calculation_line_items"
    )
    op.drop_table("calculation_line_items")
    op.drop_index(op.f("ix_readiness_findings_case_revision_id"), table_name="readiness_findings")
    op.drop_table("readiness_findings")
    op.drop_index(op.f("ix_fee_obligations_case_revision_id"), table_name="fee_obligations")
    op.drop_table("fee_obligations")
    op.drop_index(op.f("ix_contract_documents_sha256"), table_name="contract_documents")
    op.drop_index(op.f("ix_contract_documents_organization_id"), table_name="contract_documents")
    op.drop_index(op.f("ix_contract_documents_case_revision_id"), table_name="contract_documents")
    op.drop_table("contract_documents")
    op.drop_index(op.f("ix_calculation_runs_case_revision_id"), table_name="calculation_runs")
    op.drop_table("calculation_runs")
    op.drop_index(op.f("ix_case_revisions_case_id"), table_name="case_revisions")
    op.drop_table("case_revisions")
    op.drop_index(op.f("ix_rescue_cases_organization_id"), table_name="rescue_cases")
    op.drop_index("ix_rescue_cases_org_status", table_name="rescue_cases")
    op.drop_table("rescue_cases")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_idempotency_records_organization_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index("ix_audit_org_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
